/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class Simple_calculator extends javax.swing.JFrame {

    /**
     * Creates new form Simple_calculator
     */
    public Simple_calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Input1 = new javax.swing.JLabel();
        Input2 = new javax.swing.JLabel();
        T1 = new javax.swing.JTextField();
        T2 = new javax.swing.JTextField();
        Plus = new javax.swing.JToggleButton();
        Minus = new javax.swing.JToggleButton();
        Divide = new javax.swing.JToggleButton();
        Multify = new javax.swing.JToggleButton();
        Answer = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Input1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Input1.setForeground(new java.awt.Color(204, 204, 204));
        Input1.setText("  First Input ");
        getContentPane().add(Input1);
        Input1.setBounds(76, 59, 110, 17);

        Input2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Input2.setForeground(new java.awt.Color(255, 255, 255));
        Input2.setText("Second Input");
        getContentPane().add(Input2);
        Input2.setBounds(288, 59, 98, 15);
        getContentPane().add(T1);
        T1.setBounds(76, 106, 109, 20);
        getContentPane().add(T2);
        T2.setBounds(289, 106, 97, 20);

        Plus.setText("+");
        Plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlusActionPerformed(evt);
            }
        });
        getContentPane().add(Plus);
        Plus.setBounds(76, 158, 109, 23);

        Minus.setText("-");
        Minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinusActionPerformed(evt);
            }
        });
        getContentPane().add(Minus);
        Minus.setBounds(289, 158, 97, 23);

        Divide.setText("/");
        Divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivideActionPerformed(evt);
            }
        });
        getContentPane().add(Divide);
        Divide.setBounds(76, 212, 109, 23);

        Multify.setText("x");
        Multify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultifyActionPerformed(evt);
            }
        });
        getContentPane().add(Multify);
        Multify.setBounds(289, 212, 97, 23);

        Answer.setForeground(new java.awt.Color(204, 204, 204));
        getContentPane().add(Answer);
        Answer.setBounds(67, 293, 270, 25);

        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\File By name\\Image\\Dark-Phone-Wallpaper-008-500x500 (1).jpg")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 500, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinusActionPerformed
        // TODO add your handling code here:
          int result;
        getInput();
        result = n1 - n2;
        Answer.setText("The answer : "+result);
        Answer.setSize(500,100);
        
    }//GEN-LAST:event_MinusActionPerformed

    private void PlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlusActionPerformed
        // TODO add your handling code here:
        int result;
        getInput();
        result = n1 + n2;
        Answer.setText("The answer :  "+result);
        Answer.setSize(500,100);
    }//GEN-LAST:event_PlusActionPerformed

    private void DivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivideActionPerformed
        // TODO add your handling code here:
           double result;
        getInput();
        result = (double) n1 / n2;
        Answer.setText("The answer :  "+result);
        Answer.setSize(500,100);
    }//GEN-LAST:event_DivideActionPerformed

    private void MultifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultifyActionPerformed
        // TODO add your handling code here:
        long  result;
        getInput();
        result = (long)n1 * (long)n2;
        Answer.setText("The answer :  "+result);
        Answer.setSize(500,100);
    }//GEN-LAST:event_MultifyActionPerformed
       private void getInput(){
            n1 = Integer.parseInt(T1.getText());
            n2 =Integer.parseInt(T2.getText());
       }
               
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Simple_calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Simple_calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Simple_calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Simple_calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Simple_calculator().setVisible(true);
            }
        });
    }
    private int n1;
    private int n2;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Answer;
    private javax.swing.JToggleButton Divide;
    private javax.swing.JLabel Input1;
    private javax.swing.JLabel Input2;
    private javax.swing.JToggleButton Minus;
    private javax.swing.JToggleButton Multify;
    private javax.swing.JToggleButton Plus;
    private javax.swing.JTextField T1;
    private javax.swing.JTextField T2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
